### ISSUE TITLE
FAB doesn't change icon after reopening the app

### ISSUE THREAD

**Issue by polpg** [polpg/EventReminder#18]

**Comment by abhiemanyu87** [comment]
Any step to reproduce?

**Comment by polpg** [comment]
Pretty sure it has to do with this: 
https://github.com/polpg/EventReminder/blob/35d5edbf01dda72999abfa02af1d2013c89318bb/app/src/main/java/cat/polpadilla/eventreminder/MainActivity.java#L45-L58

When I leave the app open and use other apps, i guess Android clears RAM and "closes" the app. When i reopen it, the fab button doesn't update, neither does the bottomAppBar menu.
